[2025-03-18T19:23:55.247+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-18T19:23:55.270+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.bronze_ingestion manual__2025-03-18T19:18:51.027148+00:00 [queued]>
[2025-03-18T19:23:55.281+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.bronze_ingestion manual__2025-03-18T19:18:51.027148+00:00 [queued]>
[2025-03-18T19:23:55.282+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-18T19:23:55.301+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): bronze_ingestion> on 2025-03-18 19:18:51.027148+00:00
[2025-03-18T19:23:55.310+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pyspark_etl_pipeline', 'bronze_ingestion', 'manual__2025-03-18T19:18:51.027148+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmporo3p2g8']
[2025-03-18T19:23:55.313+0000] {standard_task_runner.py:105} INFO - Job 57: Subtask bronze_ingestion
[2025-03-18T19:23:55.316+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5892) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-18T19:23:55.318+0000] {standard_task_runner.py:72} INFO - Started process 5893 to run task
[2025-03-18T19:23:55.373+0000] {task_command.py:467} INFO - Running <TaskInstance: pyspark_etl_pipeline.bronze_ingestion manual__2025-03-18T19:18:51.027148+00:00 [running]> on host 022aaead3d5e
[2025-03-18T19:23:55.472+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_etl_pipeline' AIRFLOW_CTX_TASK_ID='bronze_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-03-18T19:18:51.027148+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-18T19:18:51.027148+00:00'
[2025-03-18T19:23:55.474+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-18T19:23:55.475+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-18T19:23:55.475+0000] {logging_mixin.py:190} INFO - Current task name:bronze_ingestion state:running start_date:2025-03-18 19:23:55.270967+00:00
[2025-03-18T19:23:55.476+0000] {logging_mixin.py:190} INFO - Dag name:pyspark_etl_pipeline and current dag run status:running
[2025-03-18T19:23:55.477+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-18T19:23:55.478+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-18T19:23:55.479+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/bronze_ingestion.py']
[2025-03-18T19:23:55.491+0000] {subprocess.py:99} INFO - Output:
[2025-03-18T19:23:55.493+0000] {subprocess.py:106} INFO - /usr/bin/bash: line 1: spark-submit: command not found
[2025-03-18T19:23:55.493+0000] {subprocess.py:110} INFO - Command exited with return code 127
[2025-03-18T19:23:55.507+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-03-18T19:23:55.512+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-18T19:23:55.513+0000] {logging_mixin.py:190} INFO - Task start:2025-03-18 19:23:55.270967+00:00 end:2025-03-18 19:23:55.512115+00:00 duration:0.241148
[2025-03-18T19:23:55.514+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): bronze_ingestion> dag:<DAG: pyspark_etl_pipeline> dagrun:<DagRun pyspark_etl_pipeline @ 2025-03-18 19:18:51.027148+00:00: manual__2025-03-18T19:18:51.027148+00:00, state:running, queued_at: 2025-03-18 19:18:51.049670+00:00. externally triggered: True>
[2025-03-18T19:23:55.515+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 127.
[2025-03-18T19:23:55.515+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=pyspark_etl_pipeline, task_id=bronze_ingestion, run_id=manual__2025-03-18T19:18:51.027148+00:00, execution_date=20250318T191851, start_date=20250318T192355, end_date=20250318T192355
[2025-03-18T19:23:55.546+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-18T19:23:55.547+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 57 for task bronze_ingestion (Bash command failed. The command returned a non-zero exit code 127.; 5893)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-03-18T19:23:55.586+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-18T19:23:55.620+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-18T19:23:55.625+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
