[2025-03-18T21:01:25.597+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-18T21:01:25.629+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-18T19:18:51.027148+00:00 [queued]>
[2025-03-18T21:01:25.642+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-18T19:18:51.027148+00:00 [queued]>
[2025-03-18T21:01:25.643+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-18T21:01:25.659+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): silver_ingestion> on 2025-03-18 19:18:51.027148+00:00
[2025-03-18T21:01:25.666+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pyspark_etl_pipeline', 'silver_ingestion', 'manual__2025-03-18T19:18:51.027148+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmpx4gn8h0_']
[2025-03-18T21:01:25.670+0000] {standard_task_runner.py:105} INFO - Job 68: Subtask silver_ingestion
[2025-03-18T21:01:25.671+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6546) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-18T21:01:25.672+0000] {standard_task_runner.py:72} INFO - Started process 6547 to run task
[2025-03-18T21:01:25.725+0000] {task_command.py:467} INFO - Running <TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-18T19:18:51.027148+00:00 [running]> on host f51d6b911be2
[2025-03-18T21:01:25.825+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_etl_pipeline' AIRFLOW_CTX_TASK_ID='silver_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-03-18T19:18:51.027148+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-18T19:18:51.027148+00:00'
[2025-03-18T21:01:25.826+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-18T21:01:25.845+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-18T21:01:25.847+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/silver_ingestion.py']
[2025-03-18T21:01:25.856+0000] {subprocess.py:99} INFO - Output:
[2025-03-18T21:01:29.051+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO SparkContext: Running Spark version 3.5.5
[2025-03-18T21:01:29.052+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO SparkContext: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-18T21:01:29.053+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO SparkContext: Java version 17.0.14
[2025-03-18T21:01:29.098+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-18T21:01:29.175+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO ResourceUtils: ==============================================================
[2025-03-18T21:01:29.176+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-18T21:01:29.177+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO ResourceUtils: ==============================================================
[2025-03-18T21:01:29.178+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO SparkContext: Submitted application: SilverLayer
[2025-03-18T21:01:29.195+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-18T21:01:29.202+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO ResourceProfile: Limiting resource is cpu
[2025-03-18T21:01:29.204+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-18T21:01:29.243+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO SecurityManager: Changing view acls to: default
[2025-03-18T21:01:29.244+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO SecurityManager: Changing modify acls to: default
[2025-03-18T21:01:29.244+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO SecurityManager: Changing view acls groups to:
[2025-03-18T21:01:29.245+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO SecurityManager: Changing modify acls groups to:
[2025-03-18T21:01:29.245+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-03-18T21:01:29.459+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO Utils: Successfully started service 'sparkDriver' on port 45773.
[2025-03-18T21:01:29.486+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO SparkEnv: Registering MapOutputTracker
[2025-03-18T21:01:29.519+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-18T21:01:29.536+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-18T21:01:29.536+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-18T21:01:29.541+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-18T21:01:29.564+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-85d5a89e-5dfb-4db6-8779-a241540e4764
[2025-03-18T21:01:29.576+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-18T21:01:29.591+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-18T21:01:29.717+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-18T21:01:29.786+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-18T21:01:29.904+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO Executor: Starting executor ID driver on host f51d6b911be2
[2025-03-18T21:01:29.905+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO Executor: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-18T21:01:29.906+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO Executor: Java version 17.0.14
[2025-03-18T21:01:29.913+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-03-18T21:01:29.913+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@61f102b2 for default.
[2025-03-18T21:01:29.935+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 45881.
[2025-03-18T21:01:29.936+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO NettyBlockTransferService: Server created on f51d6b911be2:45881
[2025-03-18T21:01:29.937+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-18T21:01:29.944+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, f51d6b911be2, 45881, None)
[2025-03-18T21:01:29.948+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO BlockManagerMasterEndpoint: Registering block manager f51d6b911be2:45881 with 434.4 MiB RAM, BlockManagerId(driver, f51d6b911be2, 45881, None)
[2025-03-18T21:01:29.950+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, f51d6b911be2, 45881, None)
[2025-03-18T21:01:29.952+0000] {subprocess.py:106} INFO - 25/03/18 21:01:29 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, f51d6b911be2, 45881, None)
[2025-03-18T21:01:30.463+0000] {subprocess.py:106} INFO - 25/03/18 21:01:30 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-18T21:01:30.471+0000] {subprocess.py:106} INFO - 25/03/18 21:01:30 INFO SharedState: Warehouse path is 'file:/tmp/***tmpt4roe8hs/spark-warehouse'.
[2025-03-18T21:01:31.696+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-03-18T21:01:31.697+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/silver_ingestion.py", line 13, in <module>
[2025-03-18T21:01:31.697+0000] {subprocess.py:106} INFO -     df = spark.read.option("multiline", "true").json(bronze_path)
[2025-03-18T21:01:31.698+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-18T21:01:31.698+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 425, in json
[2025-03-18T21:01:31.699+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-18T21:01:31.700+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-03-18T21:01:31.709+0000] {subprocess.py:106} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/tmp/***tmpt4roe8hs/bronze_layer.json.
[2025-03-18T21:01:31.760+0000] {subprocess.py:106} INFO - 25/03/18 21:01:31 INFO SparkContext: Invoking stop() from shutdown hook
[2025-03-18T21:01:31.760+0000] {subprocess.py:106} INFO - 25/03/18 21:01:31 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-18T21:01:31.774+0000] {subprocess.py:106} INFO - 25/03/18 21:01:31 INFO SparkUI: Stopped Spark web UI at http://f51d6b911be2:4040
[2025-03-18T21:01:31.789+0000] {subprocess.py:106} INFO - 25/03/18 21:01:31 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-18T21:01:31.803+0000] {subprocess.py:106} INFO - 25/03/18 21:01:31 INFO MemoryStore: MemoryStore cleared
[2025-03-18T21:01:31.804+0000] {subprocess.py:106} INFO - 25/03/18 21:01:31 INFO BlockManager: BlockManager stopped
[2025-03-18T21:01:31.810+0000] {subprocess.py:106} INFO - 25/03/18 21:01:31 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-18T21:01:31.813+0000] {subprocess.py:106} INFO - 25/03/18 21:01:31 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-18T21:01:31.823+0000] {subprocess.py:106} INFO - 25/03/18 21:01:31 INFO SparkContext: Successfully stopped SparkContext
[2025-03-18T21:01:31.824+0000] {subprocess.py:106} INFO - 25/03/18 21:01:31 INFO ShutdownHookManager: Shutdown hook called
[2025-03-18T21:01:31.824+0000] {subprocess.py:106} INFO - 25/03/18 21:01:31 INFO ShutdownHookManager: Deleting directory /tmp/spark-64d11e9a-1f44-498e-b24e-13931fd1bf11
[2025-03-18T21:01:31.830+0000] {subprocess.py:106} INFO - 25/03/18 21:01:31 INFO ShutdownHookManager: Deleting directory /tmp/spark-70577c89-8b37-4b37-80fe-8e2a40628c09
[2025-03-18T21:01:31.836+0000] {subprocess.py:106} INFO - 25/03/18 21:01:31 INFO ShutdownHookManager: Deleting directory /tmp/spark-70577c89-8b37-4b37-80fe-8e2a40628c09/pyspark-b128eaf6-c28c-41ab-aa0a-012fc1c4d1ec
[2025-03-18T21:01:31.869+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-18T21:01:31.882+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-18T21:01:31.889+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=pyspark_etl_pipeline, task_id=silver_ingestion, run_id=manual__2025-03-18T19:18:51.027148+00:00, execution_date=20250318T191851, start_date=20250318T210125, end_date=20250318T210131
[2025-03-18T21:01:31.890+0000] {taskinstance.py:1564} INFO - Executing callback at index 0: notify_failure
[2025-03-18T21:01:31.912+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:155 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-03-18T21:01:31.913+0000] {configuration.py:1074} WARNING - section/key [smtp/smtp_user] not found in config
[2025-03-18T21:01:31.913+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-03-18T21:01:31.916+0000] {taskinstance.py:1568} ERROR - Error in callback at index 0: notify_failure
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1566, in _run_finished_callback
    callback(context)
  File "/opt/airflow/dags/dag_pipeline.py", line 12, in notify_failure
    send_email(to=['cvsalimoliveira@gmail.com'], subject=subject, html_content=body)  #Please edit it with your email
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 155, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 274, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 318, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 865, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 850, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2025-03-18T21:01:31.945+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-18T21:01:31.945+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 68 for task silver_ingestion (Bash command failed. The command returned a non-zero exit code 1.; 6547)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-18T21:01:31.960+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-18T21:01:31.971+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
