[2025-03-19T05:19:11.088+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T05:19:11.114+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.bronze_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T05:19:11.126+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.bronze_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T05:19:11.127+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-19T05:19:11.146+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): bronze_ingestion> on 2025-03-19 05:14:09.222928+00:00
[2025-03-19T05:19:11.155+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pyspark_etl_pipeline', 'bronze_ingestion', 'manual__2025-03-19T05:14:09.222928+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmpg4unhvui']
[2025-03-19T05:19:11.159+0000] {standard_task_runner.py:105} INFO - Job 94: Subtask bronze_ingestion
[2025-03-19T05:19:11.162+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=592) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T05:19:11.164+0000] {standard_task_runner.py:72} INFO - Started process 593 to run task
[2025-03-19T05:19:11.220+0000] {task_command.py:467} INFO - Running <TaskInstance: pyspark_etl_pipeline.bronze_ingestion manual__2025-03-19T05:14:09.222928+00:00 [running]> on host ce06e3f70cd0
[2025-03-19T05:19:11.328+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='caiovos@hotmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_etl_pipeline' AIRFLOW_CTX_TASK_ID='bronze_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T05:14:09.222928+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T05:14:09.222928+00:00'
[2025-03-19T05:19:11.329+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T05:19:11.346+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-19T05:19:11.348+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/bronze_ingestion.py']
[2025-03-19T05:19:11.356+0000] {subprocess.py:99} INFO - Output:
[2025-03-19T05:19:11.358+0000] {subprocess.py:106} INFO - /usr/bin/bash: line 1: spark-submit: command not found
[2025-03-19T05:19:11.359+0000] {subprocess.py:110} INFO - Command exited with return code 127
[2025-03-19T05:19:11.372+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-03-19T05:19:11.377+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=pyspark_etl_pipeline, task_id=bronze_ingestion, run_id=manual__2025-03-19T05:14:09.222928+00:00, execution_date=20250319T051409, start_date=20250319T051911, end_date=20250319T051911
[2025-03-19T05:19:11.398+0000] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2025-03-19T05:19:11.399+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-03-19T05:19:13.742+0000] {email.py:283} INFO - Sent an alert email to ['caiovos@hotmail.com']
[2025-03-19T05:19:14.511+0000] {taskinstance.py:1564} INFO - Executing callback at index 0: notify_failure
[2025-03-19T05:19:14.520+0000] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2025-03-19T05:19:14.520+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-03-19T05:19:15.659+0000] {email.py:283} INFO - Sent an alert email to ['cvsalimoliveira@gmail.com']
[2025-03-19T05:19:16.384+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T05:19:16.384+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 94 for task bronze_ingestion (Bash command failed. The command returned a non-zero exit code 127.; 593)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-03-19T05:19:16.398+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-19T05:19:16.432+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T05:19:16.438+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
