[2025-03-18T16:25:44.228+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-18T16:25:44.251+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: medalhao_data_pipeline.run_bronze_ingestion manual__2025-03-18T16:15:41.235672+00:00 [queued]>
[2025-03-18T16:25:44.263+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: medalhao_data_pipeline.run_bronze_ingestion manual__2025-03-18T16:15:41.235672+00:00 [queued]>
[2025-03-18T16:25:44.264+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 3
[2025-03-18T16:25:44.284+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): run_bronze_ingestion> on 2025-03-18 16:15:41.235672+00:00
[2025-03-18T16:25:44.292+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'medalhao_data_pipeline', 'run_bronze_ingestion', 'manual__2025-03-18T16:15:41.235672+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/DAG_orchestration.py', '--cfg-path', '/tmp/tmpv8n0df83']
[2025-03-18T16:25:44.296+0000] {standard_task_runner.py:105} INFO - Job 39: Subtask run_bronze_ingestion
[2025-03-18T16:25:44.298+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=562) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-18T16:25:44.300+0000] {standard_task_runner.py:72} INFO - Started process 563 to run task
[2025-03-18T16:25:44.355+0000] {task_command.py:467} INFO - Running <TaskInstance: medalhao_data_pipeline.run_bronze_ingestion manual__2025-03-18T16:15:41.235672+00:00 [running]> on host 7a9daf5f19ad
[2025-03-18T16:25:44.466+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='medalhao_data_pipeline' AIRFLOW_CTX_TASK_ID='run_bronze_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-03-18T16:15:41.235672+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-18T16:15:41.235672+00:00'
[2025-03-18T16:25:44.467+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-18T16:25:44.485+0000] {DAG_orchestration.py:28} INFO - Running data quality checks
[2025-03-18T16:25:44.522+0000] {DAG_orchestration.py:14} ERROR - Execution failed for breweries_data_pipeline/bronze_ingestion.py: Command '['python3', 'breweries_data_pipeline/bronze_ingestion.py']' returned non-zero exit status 2.
[2025-03-18T16:25:44.523+0000] {DAG_orchestration.py:24} WARNING - Slack webhook URL not set
[2025-03-18T16:25:44.523+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/DAG_orchestration.py", line 29, in bronze_layer
    execute_script("breweries_data_pipeline/bronze_ingestion.py")
  File "/opt/airflow/dags/DAG_orchestration.py", line 12, in execute_script
    subprocess.run(["python3", script_path], check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 573, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', 'breweries_data_pipeline/bronze_ingestion.py']' returned non-zero exit status 2.
[2025-03-18T16:25:44.535+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=medalhao_data_pipeline, task_id=run_bronze_ingestion, run_id=manual__2025-03-18T16:15:41.235672+00:00, execution_date=20250318T161541, start_date=20250318T162544, end_date=20250318T162544
[2025-03-18T16:25:44.564+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-18T16:25:44.565+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 39 for task run_bronze_ingestion (Command '['python3', 'breweries_data_pipeline/bronze_ingestion.py']' returned non-zero exit status 2.; 563)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/DAG_orchestration.py", line 29, in bronze_layer
    execute_script("breweries_data_pipeline/bronze_ingestion.py")
  File "/opt/airflow/dags/DAG_orchestration.py", line 12, in execute_script
    subprocess.run(["python3", script_path], check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 573, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', 'breweries_data_pipeline/bronze_ingestion.py']' returned non-zero exit status 2.
[2025-03-18T16:25:44.612+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-18T16:25:44.643+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-18T16:25:44.648+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
