[2025-03-18T18:20:52.453+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-18T18:20:52.473+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: medalhao_data_pipeline.run_bronze_ingestion manual__2025-03-18T16:15:41.235672+00:00 [queued]>
[2025-03-18T18:20:52.483+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: medalhao_data_pipeline.run_bronze_ingestion manual__2025-03-18T16:15:41.235672+00:00 [queued]>
[2025-03-18T18:20:52.483+0000] {taskinstance.py:2867} INFO - Starting attempt 7 of 8
[2025-03-18T18:20:52.502+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): run_bronze_ingestion> on 2025-03-18 16:15:41.235672+00:00
[2025-03-18T18:20:52.512+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'medalhao_data_pipeline', 'run_bronze_ingestion', 'manual__2025-03-18T16:15:41.235672+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/DAG_orchestration.py', '--cfg-path', '/tmp/tmpgtljwrai']
[2025-03-18T18:20:52.514+0000] {standard_task_runner.py:105} INFO - Job 49: Subtask run_bronze_ingestion
[2025-03-18T18:20:52.518+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4421) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-18T18:20:52.519+0000] {standard_task_runner.py:72} INFO - Started process 4447 to run task
[2025-03-18T18:20:52.573+0000] {task_command.py:467} INFO - Running <TaskInstance: medalhao_data_pipeline.run_bronze_ingestion manual__2025-03-18T16:15:41.235672+00:00 [running]> on host 67bf2817aa1f
[2025-03-18T18:20:52.665+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='medalhao_data_pipeline' AIRFLOW_CTX_TASK_ID='run_bronze_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-03-18T16:15:41.235672+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-18T16:15:41.235672+00:00'
[2025-03-18T18:20:52.667+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-18T18:20:52.668+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-18T18:20:52.668+0000] {logging_mixin.py:190} INFO - Current task name:run_bronze_ingestion state:running start_date:2025-03-18 18:20:52.474138+00:00
[2025-03-18T18:20:52.668+0000] {logging_mixin.py:190} INFO - Dag name:medalhao_data_pipeline and current dag run status:running
[2025-03-18T18:20:52.669+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-18T18:20:52.670+0000] {DAG_orchestration.py:28} INFO - Running data quality checks
[2025-03-18T18:20:52.716+0000] {DAG_orchestration.py:14} ERROR - Execution failed for bronze_ingestion.py: Command '['python3', 'bronze_ingestion.py']' returned non-zero exit status 2.
[2025-03-18T18:20:52.717+0000] {DAG_orchestration.py:24} WARNING - Slack webhook URL not set
[2025-03-18T18:20:52.718+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/DAG_orchestration.py", line 29, in bronze_layer
    execute_script("bronze_ingestion.py")
  File "/opt/airflow/dags/DAG_orchestration.py", line 12, in execute_script
    subprocess.run(["python3", script_path], check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 573, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', 'bronze_ingestion.py']' returned non-zero exit status 2.
[2025-03-18T18:20:52.736+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-18T18:20:52.737+0000] {logging_mixin.py:190} INFO - Task start:2025-03-18 18:20:52.474138+00:00 end:2025-03-18 18:20:52.735980+00:00 duration:0.261842
[2025-03-18T18:20:52.737+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): run_bronze_ingestion> dag:<DAG: medalhao_data_pipeline> dagrun:<DagRun medalhao_data_pipeline @ 2025-03-18 16:15:41.235672+00:00: manual__2025-03-18T16:15:41.235672+00:00, state:running, queued_at: 2025-03-18 18:15:48.446164+00:00. externally triggered: True>
[2025-03-18T18:20:52.738+0000] {logging_mixin.py:190} INFO - Failure caused by Command '['python3', 'bronze_ingestion.py']' returned non-zero exit status 2.
[2025-03-18T18:20:52.739+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=medalhao_data_pipeline, task_id=run_bronze_ingestion, run_id=manual__2025-03-18T16:15:41.235672+00:00, execution_date=20250318T161541, start_date=20250318T182052, end_date=20250318T182052
[2025-03-18T18:20:52.776+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-18T18:20:52.777+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 49 for task run_bronze_ingestion (Command '['python3', 'bronze_ingestion.py']' returned non-zero exit status 2.; 4447)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/DAG_orchestration.py", line 29, in bronze_layer
    execute_script("bronze_ingestion.py")
  File "/opt/airflow/dags/DAG_orchestration.py", line 12, in execute_script
    subprocess.run(["python3", script_path], check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 573, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', 'bronze_ingestion.py']' returned non-zero exit status 2.
[2025-03-18T18:20:52.823+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-18T18:20:52.853+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-18T18:20:52.855+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
