[2025-03-18T21:01:36.794+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-18T21:01:36.823+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-18T20:56:22.390623+00:00 [queued]>
[2025-03-18T21:01:36.837+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-18T20:56:22.390623+00:00 [queued]>
[2025-03-18T21:01:36.837+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-18T21:01:36.855+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): silver_ingestion> on 2025-03-18 20:56:22.390623+00:00
[2025-03-18T21:01:36.863+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pyspark_etl_pipeline', 'silver_ingestion', 'manual__2025-03-18T20:56:22.390623+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmphkl31ong']
[2025-03-18T21:01:36.866+0000] {standard_task_runner.py:105} INFO - Job 69: Subtask silver_ingestion
[2025-03-18T21:01:36.868+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6689) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-18T21:01:36.869+0000] {standard_task_runner.py:72} INFO - Started process 6690 to run task
[2025-03-18T21:01:36.922+0000] {task_command.py:467} INFO - Running <TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-18T20:56:22.390623+00:00 [running]> on host f51d6b911be2
[2025-03-18T21:01:37.022+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_etl_pipeline' AIRFLOW_CTX_TASK_ID='silver_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-03-18T20:56:22.390623+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-18T20:56:22.390623+00:00'
[2025-03-18T21:01:37.023+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-18T21:01:37.040+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-18T21:01:37.041+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/silver_ingestion.py']
[2025-03-18T21:01:37.051+0000] {subprocess.py:99} INFO - Output:
[2025-03-18T21:01:39.548+0000] {subprocess.py:106} INFO - 25/03/18 21:01:39 INFO SparkContext: Running Spark version 3.5.5
[2025-03-18T21:01:39.551+0000] {subprocess.py:106} INFO - 25/03/18 21:01:39 INFO SparkContext: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-18T21:01:39.552+0000] {subprocess.py:106} INFO - 25/03/18 21:01:39 INFO SparkContext: Java version 17.0.14
[2025-03-18T21:01:39.622+0000] {subprocess.py:106} INFO - 25/03/18 21:01:39 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-18T21:01:39.737+0000] {subprocess.py:106} INFO - 25/03/18 21:01:39 INFO ResourceUtils: ==============================================================
[2025-03-18T21:01:39.739+0000] {subprocess.py:106} INFO - 25/03/18 21:01:39 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-18T21:01:39.741+0000] {subprocess.py:106} INFO - 25/03/18 21:01:39 INFO ResourceUtils: ==============================================================
[2025-03-18T21:01:39.742+0000] {subprocess.py:106} INFO - 25/03/18 21:01:39 INFO SparkContext: Submitted application: SilverLayer
[2025-03-18T21:01:39.775+0000] {subprocess.py:106} INFO - 25/03/18 21:01:39 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-18T21:01:39.788+0000] {subprocess.py:106} INFO - 25/03/18 21:01:39 INFO ResourceProfile: Limiting resource is cpu
[2025-03-18T21:01:39.789+0000] {subprocess.py:106} INFO - 25/03/18 21:01:39 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-18T21:01:39.855+0000] {subprocess.py:106} INFO - 25/03/18 21:01:39 INFO SecurityManager: Changing view acls to: default
[2025-03-18T21:01:39.856+0000] {subprocess.py:106} INFO - 25/03/18 21:01:39 INFO SecurityManager: Changing modify acls to: default
[2025-03-18T21:01:39.857+0000] {subprocess.py:106} INFO - 25/03/18 21:01:39 INFO SecurityManager: Changing view acls groups to:
[2025-03-18T21:01:39.858+0000] {subprocess.py:106} INFO - 25/03/18 21:01:39 INFO SecurityManager: Changing modify acls groups to:
[2025-03-18T21:01:39.859+0000] {subprocess.py:106} INFO - 25/03/18 21:01:39 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-03-18T21:01:40.157+0000] {subprocess.py:106} INFO - 25/03/18 21:01:40 INFO Utils: Successfully started service 'sparkDriver' on port 41275.
[2025-03-18T21:01:40.300+0000] {subprocess.py:106} INFO - 25/03/18 21:01:40 INFO SparkEnv: Registering MapOutputTracker
[2025-03-18T21:01:40.352+0000] {subprocess.py:106} INFO - 25/03/18 21:01:40 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-18T21:01:40.390+0000] {subprocess.py:106} INFO - 25/03/18 21:01:40 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-18T21:01:40.392+0000] {subprocess.py:106} INFO - 25/03/18 21:01:40 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-18T21:01:40.404+0000] {subprocess.py:106} INFO - 25/03/18 21:01:40 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-18T21:01:40.441+0000] {subprocess.py:106} INFO - 25/03/18 21:01:40 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-2a4f840c-8e85-4040-987f-956b341af5e3
[2025-03-18T21:01:40.459+0000] {subprocess.py:106} INFO - 25/03/18 21:01:40 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-18T21:01:40.478+0000] {subprocess.py:106} INFO - 25/03/18 21:01:40 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-18T21:01:40.690+0000] {subprocess.py:106} INFO - 25/03/18 21:01:40 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-18T21:01:40.771+0000] {subprocess.py:106} INFO - 25/03/18 21:01:40 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-18T21:01:40.899+0000] {subprocess.py:106} INFO - 25/03/18 21:01:40 INFO Executor: Starting executor ID driver on host f51d6b911be2
[2025-03-18T21:01:40.900+0000] {subprocess.py:106} INFO - 25/03/18 21:01:40 INFO Executor: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-18T21:01:40.901+0000] {subprocess.py:106} INFO - 25/03/18 21:01:40 INFO Executor: Java version 17.0.14
[2025-03-18T21:01:40.910+0000] {subprocess.py:106} INFO - 25/03/18 21:01:40 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-03-18T21:01:40.910+0000] {subprocess.py:106} INFO - 25/03/18 21:01:40 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@61f102b2 for default.
[2025-03-18T21:01:40.931+0000] {subprocess.py:106} INFO - 25/03/18 21:01:40 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 44015.
[2025-03-18T21:01:40.932+0000] {subprocess.py:106} INFO - 25/03/18 21:01:40 INFO NettyBlockTransferService: Server created on f51d6b911be2:44015
[2025-03-18T21:01:40.934+0000] {subprocess.py:106} INFO - 25/03/18 21:01:40 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-18T21:01:40.941+0000] {subprocess.py:106} INFO - 25/03/18 21:01:40 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, f51d6b911be2, 44015, None)
[2025-03-18T21:01:40.945+0000] {subprocess.py:106} INFO - 25/03/18 21:01:40 INFO BlockManagerMasterEndpoint: Registering block manager f51d6b911be2:44015 with 434.4 MiB RAM, BlockManagerId(driver, f51d6b911be2, 44015, None)
[2025-03-18T21:01:40.948+0000] {subprocess.py:106} INFO - 25/03/18 21:01:40 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, f51d6b911be2, 44015, None)
[2025-03-18T21:01:40.949+0000] {subprocess.py:106} INFO - 25/03/18 21:01:40 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, f51d6b911be2, 44015, None)
[2025-03-18T21:01:41.695+0000] {subprocess.py:106} INFO - 25/03/18 21:01:41 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-18T21:01:41.708+0000] {subprocess.py:106} INFO - 25/03/18 21:01:41 INFO SharedState: Warehouse path is 'file:/tmp/***tmpux9cndpk/spark-warehouse'.
[2025-03-18T21:01:42.872+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-03-18T21:01:42.873+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/silver_ingestion.py", line 13, in <module>
[2025-03-18T21:01:42.873+0000] {subprocess.py:106} INFO -     df = spark.read.option("multiline", "true").json(bronze_path)
[2025-03-18T21:01:42.874+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-18T21:01:42.874+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 425, in json
[2025-03-18T21:01:42.875+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-18T21:01:42.876+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-03-18T21:01:42.885+0000] {subprocess.py:106} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/tmp/***tmpux9cndpk/bronze_layer.json.
[2025-03-18T21:01:42.941+0000] {subprocess.py:106} INFO - 25/03/18 21:01:42 INFO SparkContext: Invoking stop() from shutdown hook
[2025-03-18T21:01:42.942+0000] {subprocess.py:106} INFO - 25/03/18 21:01:42 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-18T21:01:42.956+0000] {subprocess.py:106} INFO - 25/03/18 21:01:42 INFO SparkUI: Stopped Spark web UI at http://f51d6b911be2:4040
[2025-03-18T21:01:42.970+0000] {subprocess.py:106} INFO - 25/03/18 21:01:42 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-18T21:01:42.983+0000] {subprocess.py:106} INFO - 25/03/18 21:01:42 INFO MemoryStore: MemoryStore cleared
[2025-03-18T21:01:42.984+0000] {subprocess.py:106} INFO - 25/03/18 21:01:42 INFO BlockManager: BlockManager stopped
[2025-03-18T21:01:42.989+0000] {subprocess.py:106} INFO - 25/03/18 21:01:42 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-18T21:01:42.993+0000] {subprocess.py:106} INFO - 25/03/18 21:01:42 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-18T21:01:43.001+0000] {subprocess.py:106} INFO - 25/03/18 21:01:43 INFO SparkContext: Successfully stopped SparkContext
[2025-03-18T21:01:43.002+0000] {subprocess.py:106} INFO - 25/03/18 21:01:43 INFO ShutdownHookManager: Shutdown hook called
[2025-03-18T21:01:43.003+0000] {subprocess.py:106} INFO - 25/03/18 21:01:43 INFO ShutdownHookManager: Deleting directory /tmp/spark-91069749-9322-464e-bf7d-6a90fd016c0b
[2025-03-18T21:01:43.010+0000] {subprocess.py:106} INFO - 25/03/18 21:01:43 INFO ShutdownHookManager: Deleting directory /tmp/spark-8ddc09a3-ac73-4012-b461-92fcb3541cf6
[2025-03-18T21:01:43.015+0000] {subprocess.py:106} INFO - 25/03/18 21:01:43 INFO ShutdownHookManager: Deleting directory /tmp/spark-8ddc09a3-ac73-4012-b461-92fcb3541cf6/pyspark-c2ab13d0-d7f1-409c-a26f-ba5c9b96097b
[2025-03-18T21:01:43.045+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-18T21:01:43.057+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-18T21:01:43.063+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=pyspark_etl_pipeline, task_id=silver_ingestion, run_id=manual__2025-03-18T20:56:22.390623+00:00, execution_date=20250318T205622, start_date=20250318T210136, end_date=20250318T210143
[2025-03-18T21:01:43.063+0000] {taskinstance.py:1564} INFO - Executing callback at index 0: notify_failure
[2025-03-18T21:01:43.078+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:155 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-03-18T21:01:43.079+0000] {configuration.py:1074} WARNING - section/key [smtp/smtp_user] not found in config
[2025-03-18T21:01:43.079+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-03-18T21:01:43.080+0000] {taskinstance.py:1568} ERROR - Error in callback at index 0: notify_failure
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1566, in _run_finished_callback
    callback(context)
  File "/opt/airflow/dags/dag_pipeline.py", line 12, in notify_failure
    send_email(to=['cvsalimoliveira@gmail.com'], subject=subject, html_content=body)  #Please edit it with your email
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 155, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 274, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 318, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 865, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 850, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2025-03-18T21:01:43.108+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-18T21:01:43.109+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 69 for task silver_ingestion (Bash command failed. The command returned a non-zero exit code 1.; 6690)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-18T21:01:43.155+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-18T21:01:43.188+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-18T21:01:43.193+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
